config/routes.rb
Rails.application.routes.draw do
  resources :types

  resources :services

  get 'sessions/new'

  resources :users

  get 'auth/login'

  get 'home/index'

  root 'home#index'

  get 'login'  =>  'sessions#new'
  post 'login' =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'  

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user

 def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("alteracoes like ?", "%#{query}%") 
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    if session[:user]
      @user = session[:user]
      @user_logged = @user["name"]

      else
      redirect_to(login_path) 
    end
    @services = Service.search(params[:search]).paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
  end

  # GET /services/1
  # GET /services/1.json
  def show
    if session[:user]
      @user = session[:user]
      @user_logged = @user["name"]
      else
      redirect_to(login_path) 
    end
  end

  # GET /services/new
  def new
    if session[:user]
      @user = session[:user]
      @user_logged = @user["name"]
      puts session[:user]
      puts Time.now - 86400
      @t = Time.now - 86400
      puts @t.strftime("%A")

      else
      redirect_to(login_path) 
    end
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
 
    @service = Service.new(service_params)

    
    
    respond_to do |format|
      if @service.save
        @user = session[:user]
        @user_nome = @user["nome"]
        
        @user_email = @user["email"]
        contato = @user_nome
        email = @user_email
        puts @service.id
        service = Service.find(@service.id)
        ContactMailer.contact_message(contato, service, email).deliver
        
        format.html { redirect_to root_path, notice: 'Serviço cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to services_url, notice: 'Serviço cadastrado com sucesso!' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Serviço cadastrado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:user_id, :bk_web, :bk_glpi, :bk_diarias, :bk_ldap, :bkp_dns, :bk_pagina, :bk_mentor, :bk_dhcp, :bk_opera, :bk_abacus, :bk_sisconsig, :bk_antivirus, :bk_sigadaer, :bk_email, :bk_atis, :ck_sala, :ck_xen, :ck_virtuais, :ck_intraer, :ck_internet, :ck_pagina, :ck_email, :ck_sigadaer, :ck_sims, :dia_semana, :alteracoes, :cksalam, :cksalat, :cksalan, :ckxenm, :ckxent, :ckxenn, :ckvirm, :ckvirt, :ckvirn, :ckintm, :ckintt, :ckintn, :ckpagem, :ckpaget, :ckpagen, :ckinterm, :ckintert, :ckintern, :ckemailm, :ckemailt, :ckemailn, :cksigm, :cksigt, :cksign, :cksimm, :cksimt, :cksimn )
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_menuperm.html.erb
<nav style="">
  <ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Adicionar Serviço', :controller => 'services', :action => 'new' %></li>
        <li><a href="#">NPA</a></li>
       
        <li><a href="#">FAQ</a></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<%
    
    @usuario = session[:type]

    @tipo_user = Type.where(:id => @usuario).first
    puts @tipo_user.id
   ## Validando usuario para pegar menu correspondente
    if(@tipo_user.id == 2)
      
      %>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Adicionar Serviço', :controller => 'services', :action => 'new' %></li>
        <li><a href="/npaeti.pdf" target="_blank">NPA</a></li>
       
        
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 1)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'index' %></li>
       
        
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 3)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'index' %></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%

    end
%>
<div class="form_service" style="width:950px; margin-left:10%; padding-right:90px;">
<p id="notice"><%= notice %></p>
<center><h2 style="color:#hhhhhh;">Lista de Serviços</h2></center>
<br><br /><br /><br />


  <%= form_tag(services_path, :method => "get", class: "navbar-form", id: "search-form", :style => 'margin-left:30px;') do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Buscar Serviço", :style => 'width:82%; padding:8px;' %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
      <button class="btn" type="submit" style="padding:8px;">Buscar</button>
    </div>
  <% end %>
<br>

<div class="CSSTableGenerator" >
<table>
  <thead>
    <tr>
      <th>Militar</th>
      
      <th>Dia semana</th>
      <th>Data</th>
      <th>Alteracoes</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.user.name %></td>
        
        <td><%= service.dia_semana %></td>
        <td><%= service.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= service.alteracoes %></td>
        <td><%= link_to 'Abrir', service %></td>
      
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<div style="float:left; margin-left:30px; ">
<%= will_paginate @services, :previous_label => 'Anterior', :next_label => 'Próximo' %>
</div>
<br /><br /><br /><br />

<%
    
    @usuario = session[:type]

    @tipo_user = Type.where(:id => @usuario).first
    puts @tipo_user.id
   ## Validando usuario para pegar menu correspondente
    if(@tipo_user.id == 2)
   
   link_to 'Adicionar passagem', new_service_path, :style => 'width: 120px; border:none; background:#ccc; color:#000; margin-left:30px; padding:8px;'
    end


%>
</div>

app/views/services/new.html.erb
<%
    
    @usuario = session[:type]

    @tipo_user = Type.where(:id => @usuario).first
    puts @tipo_user.id
   ## Validando usuario para pegar menu correspondente
    if(@tipo_user.id == 2)
      
      %>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Adicionar Serviço', :controller => 'services', :action => 'new' %></li>
        <li><a href="#">NPA</a></li>
       
        <li><a href="#">FAQ</a></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 1)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'new' %></li>
       
        <li><a href="#">FAQ</a></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 3)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'new' %></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%

    end
%>


<%= render 'form' %>

app/views/services/show.html.erb
<%
    
    @usuario = session[:type]

    @tipo_user = Type.where(:id => @usuario).first
    puts @tipo_user.id
   ## Validando usuario para pegar menu correspondente
    if(@tipo_user.id == 2)
      
      %>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Adicionar Serviço', :controller => 'services', :action => 'new' %></li>
        <li><a href="/npaeti.pdf" target="_blank">NPA</a></li>
       
        
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 1)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'index' %></li>
       
        
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 3)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'index' %></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%

    end
%>

<br /><br /><br />

<% 

if @service.bk_web == ""
  @service.bk_web == "Backup não disponivel para o dia do serviço!"
end

if @service.bk_glpi == ""
  @service.bk_glpi == "Backup não disponivel para o dia do serviço!"
end

if @service.bk_diarias == ""
  @service.bk_diarias == "Backup não disponivel para o dia do serviço!"
end
 %>

<div class="form_service">
<p id="notice"><%= notice %></p>

<p>
  <strong>Militar:</strong>
  <%= @service.user.name %>
</p>
<hr />
<br />
<fieldset style="padding:15px;">
<legend>BACKUP DOS SERVIDORES</legend>
<p>
  <strong>Ordem de Serviço EIE(16.202):</strong>
  <% if @service.bk_web  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>GLPI(16.70):</strong>
  <% if @service.bk_glpi  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>Diárias(16.85):</strong>
  <% if @service.bk_diarias  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>LDAP(16.1):</strong>
  <% if @service.bk_ldap  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>DNS(16.2):</strong>
  <% if @service.bkp_dns  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>Página BACG(16.203):</strong>
  <% if @service.bk_pagina  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>MENTOR(16.71):</strong>
  <% if @service.bk_mentor  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>DHCP(16.33):</strong>
  <% if @service.bk_dhcp  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>OPERA(16.100):</strong>
  <% if @service.bk_opera  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>ABACUS(16.34):</strong>
  <% if @service.bk_abacus  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>SISCONSIG SGH (16.32):</strong>
  <% if @service.bk_sisconsig  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>Antívirus(16.27):</strong>
  <% if @service.bk_antivirus  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>SIGADAER(16.8):</strong>
  <% if @service.bk_sigadaer  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>Email(16.6):</strong>
  <% if @service.bk_email  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>ATIS(16.202):</strong>
  <% if @service.bk_atis  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
<p>
  <strong>NÁGIOS(16.80):</strong>
  <% if @service.bk_nagios  %>
  <%= "Backup Realizado." %>
  <% else %>
  <%= "Backup não Realizado." %>
  <% end %>
</p>
</fieldset>
<br />
<fieldset style="padding:15px;">
<legend>CHECK LIST</legend>
<p>
  <strong>SALA DOS SERVIDORES:</strong>
  <% if @service.cksalam  %>
  <%= " Manhã: Sim" %>
  <% else %>
  <%= "Manhã: Não" %>
  <% end %>
    <% if @service.cksalat  %>
  <%= "| Tarde: Sim" %>
  <% else %>
  <%= "| Tarde: Não" %>
  <% end %>
  <% if @service.cksalan  %>
  <%= "| Noite: Sim" %>
  <% else %>
  <%= "| Noite: Não" %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>SERVIDORES XEN:</strong>
  <% if @service.ckxenm  %>
  <%= " Manhã: Sim" %>
  <% else %>
  <%= "Manhã: Não" %>
  <% end %>
    <% if @service.ckxent  %>
  <%= "| Tarde: Sim" %>
  <% else %>
  <%= "| Tarde: Não" %>
  <% end %>
  <% if @service.ckxenn  %>
  <%= "| Noite: Sim" %>
  <% else %>
  <%= "| Noite: Não" %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>SERVIDORES VIRTUAIS:</strong>
  <% if @service.ckvirm  %>
  <%= " Manhã: Sim" %>
  <% else %>
  <%= "Manhã: Não" %>
  <% end %>
    <% if @service.ckvirt  %>
  <%= "| Tarde: Sim" %>
  <% else %>
  <%= "| Tarde: Não" %>
  <% end %>
  <% if @service.ckvirn  %>
  <%= "| Noite: Sim" %>
  <% else %>
  <%= "| Noite: Não" %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>INTRAER:</strong>
  <% if @service.ckintm  %>
  <%= " Manhã: Sim" %>
  <% else %>
  <%= "Manhã: Não" %>
  <% end %>
    <% if @service.ckintt  %>
  <%= "| Tarde: Sim" %>
  <% else %>
  <%= "| Tarde: Não" %>
  <% end %>
  <% if @service.ckintn  %>
  <%= "| Noite: Sim" %>
  <% else %>
  <%= "| Noite: Não" %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>INTERNET:</strong>
  <% if @service.ckinterm  %>
  <%= " Manhã: Sim" %>
  <% else %>
  <%= "Manhã: Não" %>
  <% end %>
    <% if @service.ckintert  %>
  <%= "| Tarde: Sim" %>
  <% else %>
  <%= "| Tarde: Não" %>
  <% end %>
  <% if @service.ckintern  %>
  <%= "| Noite: Sim" %>
  <% else %>
  <%= "| Noite: Não" %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>PÁGINA DA BACG:</strong>
  <% if @service.ckpagem  %>
  <%= " Manhã: Sim" %>
  <% else %>
  <%= "Manhã: Não" %>
  <% end %>
    <% if @service.ckpaget  %>
  <%= "| Tarde: Sim" %>
  <% else %>
  <%= "| Tarde: Não" %>
  <% end %>
  <% if @service.ckpagen  %>
  <%= "| Noite: Sim" %>
  <% else %>
  <%= "| Noite: Não" %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>EMAIL:</strong>
  <% if @service.ckemailm  %>
  <%= " Manhã: Sim" %>
  <% else %>
  <%= "Manhã: Não" %>
  <% end %>
    <% if @service.ckemailt  %>
  <%= "| Tarde: Sim" %>
  <% else %>
  <%= "| Tarde: Não" %>
  <% end %>
  <% if @service.ckemailn  %>
  <%= "| Noite: Sim" %>
  <% else %>
  <%= "| Noite: Não" %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>SIGADAER:</strong>
  <% if @service.cksigm  %>
  <%= " Manhã: Sim" %>
  <% else %>
  <%= "Manhã: Não" %>
  <% end %>
    <% if @service.cksigt  %>
  <%= "| Tarde: Sim" %>
  <% else %>
  <%= "| Tarde: Não" %>
  <% end %>
  <% if @service.cksign  %>
  <%= "| Noite: Sim" %>
  <% else %>
  <%= "| Noite: Não" %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>SIMS:</strong>
  <% if @service.cksimm  %>
  <%= " Manhã: Sim" %>
  <% else %>
  <%= "Manhã: Não" %>
  <% end %>
    <% if @service.cksimt  %>
  <%= "| Tarde: Sim" %>
  <% else %>
  <%= "| Tarde: Não" %>
  <% end %>
  <% if @service.cksimn  %>
  <%= "| Noite: Sim" %>
  <% else %>
  <%= "| Noite: Não" %>
  <% end %>
</p>
<hr />
<br>
<p>
  <strong>DIA DA SEMANA:</strong>
  <%= @service.dia_semana %>
</p>
<hr />
<br>
<p>
  <strong>ALTERAÇÕES:</strong>
  <%= @service.alteracoes %>
</p>
</fieldset>
</div>

<%= link_to 'Voltar', services_path, :style => 'width: 120px; border:none; background:#ccc; color:#000; margin-left:30px; padding:8px;' %>