config/routes.rb
Rails.application.routes.draw do
  resources :types

  resources :services

  get 'sessions/new'

  resources :users

  get 'auth/login'

  get 'home/index'

  root 'home#index'

  get 'login'  =>  'sessions#new'
  post 'login' =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'  

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário deletado com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :password, :name, :graduation, :email, :type_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :type_id %><span>1 - Admin | 2 - Permanência | 3 - Chefia</span>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Graduação' %><br>
    <%= f.text_field :graduation %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit  'Criar Usuário' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%
    
    @usuario = session[:type]

    @tipo_user = Type.where(:id => @usuario).first
    puts @tipo_user.id
   ## Validando usuario para pegar menu correspondente
    if(@tipo_user.id == 2)
      
      %>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Adicionar Serviço', :controller => 'services', :action => 'new' %></li>
        <li><a href="#">NPA</a></li>
       
        <li><a href="#">FAQ</a></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 1)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'index' %></li>
       
        <li><a href="#">FAQ</a></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 3)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'index' %></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%

    end
%>

<div class="form_service" style="width:950px; margin-left:10%; padding-right:90px;">
<p id="notice"><%= notice %></p>

<h1>Usuários</h1>
<div class="CSSTableGenerator" style="width:100%;">

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Senha</th>
      <th>Nome</th>
      <th>Graduação</th>
      <th>Email</th>
      <th>Tipo de usuário</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.password %></td>
        <td><%= user.name %></td>
        <td><%= user.graduation %></td>
        <td><%= user.email %></td>
        <% @tipo = Type.where(:id => user.type_id).first %>
        <td><%= @tipo.name %></td>
        <td><%= link_to 'Visualizar', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Excluir', user, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'Criar novo usuário', new_user_path %>
</div>

app/views/users/new.html.erb
<%
    
    @usuario = session[:type]

    @tipo_user = Type.where(:id => @usuario).first
    puts @tipo_user.id
   ## Validando usuario para pegar menu correspondente
    if(@tipo_user.id == 2)
      
      %>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Adicionar Serviço', :controller => 'services', :action => 'new' %></li>
        <li><a href="#">NPA</a></li>
       
        <li><a href="#">FAQ</a></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 1)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'new' %></li>
       
        <li><a href="#">FAQ</a></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 3)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'new' %></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%

    end
%>
<div class="form_service">
<h1>Novo Usuário</h1>
<br /><br />
<%= render 'form' %>

<%= link_to 'Voltar', users_path %>
</div>

app/views/users/show.html.erb
<%
    
    @usuario = session[:type]

    @tipo_user = Type.where(:id => @usuario).first
    puts @tipo_user.id
   ## Validando usuario para pegar menu correspondente
    if(@tipo_user.id == 2)
      
      %>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Adicionar Serviço', :controller => 'services', :action => 'new' %></li>
        <li><a href="#">NPA</a></li>
       
        <li><a href="#">FAQ</a></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 1)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'index' %></li>
       
        <li><a href="#">FAQ</a></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%
    end

    if(@tipo_user.id == 3)

%>
<nav style="">
<ul class="menu">
        <li style="padding:5px;">Bem vindo, <% @user_logged %>&nbsp;&nbsp;&nbsp;</li>
        <li><%= link_to 'Usuários', :controller => 'users', :action => 'index' %></li>
        <li><%= link_to 'Serviços', :controller => 'services', :action => 'index' %></li>
        <li><%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Tem certeza?' } %></li>               
</ul>
</nav>
      <%

    end
%>

<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Graduação:</strong>
  <%= @user.graduation %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>